config/routes.rb
Rails.application.routes.draw do
  root to: 'static#index'

  get "/newcommute", to: "static#newcommute", as: "newcommute"
  get "/commuteslist", to: "static#commuteslist", as: "commuteslist"
  get "/api/passengercommutes", to: "api_passenger_commutes#retrieve", as: "APIPassengerCommutes"
  get "/drivercommutes/requestinfo", to: "drivercommutes#retrieve", as: "drivercommutes_retrieve"
  get "/passengercommutes/requestinfo", to: "passengercommutes#retrieve", as: "passengercommutes_retrieve"
  get "/goodbye", to: "static#exit", as: "exit"
  resources :map, only: [:index]
  resource :session, only: [:new, :create, :destroy]

  resources :users

  resources :drivercommutes, only: [:create, :destroy, :update]
  resources :passengercommutes, only: [:create, :destroy, :update]
  resources :places, only: [:create, :destroy, :show, :index]
  resource :reviews, only: [:create, :destroy, :show]
  resources :requests, only: [:create, :destroy, :index, :update]
  resources :twilio, only: [:create, :index]
  
end

app/models/user.rb
class User < ActiveRecord::Base
  mount_uploader :picture, AvatarUploader
  has_many :drivercommutes
  has_many :passengercommutes
  has_many :places
  has_secure_password

  validates :email, presence: true, uniqueness: true
  validates :phone, presence: true
  validates :firstname, presence: true
  validates :lastname, presence: true
  validates :password, length: { in: 1..20}, on: :create
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @user = current_user
    @users = User.all
    @reviews = Review.where(reviewee_id: current_user.id)
  end
  
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    @user.phone = "+"+params["phone1"]+params["phone2"]+params["phone3"]

    if @user.save
      session[:user_id] = @user.id
      redirect_to places_path
    else
      render :new
    end
  end

  def show
    @user = User.where(id: params[:id]).first
    @users = User.all
    @review = Review.new
    @reviews = Review.where(reviewee_id: params[:id])
  end

  # helper method
  def user_params
    params.require(:user).permit(:firstname, :lastname, :email, :bio, :password, :password_confirmation, :picture)
  end

  
end

app/views/users/_userform.html.erb
<%= form_for @user, :html=>{:multipart => true} do |f| %>

  <% if @user.errors.any? %>
    <div>
      <%= pluralize(@user.errors.count, "error") %> prevented this user from being created:
      <ul>
        <% @user.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= f.label "firstname", "First Name" %><br>
    <%= f.text_field "firstname", class:"form-control" %>
  </div>
  <div>
    <%= f.label "lastname", "Last Name" %><br>
    <%= f.text_field "lastname", class:"form-control" %>
  </div>
  <div>
    <%= f.label "email", "Email" %><br>
    <%= f.text_field "email", class:"form-control" %>
  </div>
  <div>
    <%= f.label "phone", "Phone" %><br>
    <%= text_field_tag :phone1, nil, placeholder: "604", size: 4 %>
    <%= text_field_tag :phone2, nil, placeholder: "555", size: 5 %>
    <%= text_field_tag :phone3, nil, placeholder: "5555", size:5 %>
  </div><br>
  <div>
    <%= f.label :picture, "Profile Picture" %><br>
    <%= f.file_field :picture %> <br>
  </div>

  <div>
    <%= f.label "industry", "Industry" %>
    <br>
    <%= f.select :industry, options_for_select(["agriculture","energy","entertainment","finance","government","health/medical","hospitality","marketing/communications","non-profit","publishing","science","technology","transportation"]) %>
  </div>

  <div>
    <%= f.label "bio", "Bio" %><br>
    <%= f.text_area "bio", placeholder: "Tell other users a bit about yourself!", class:"form-control" %>
  </div>

  <div>
    <%= f.label "linkedin", "LinkedIn (optional)" %><br>
    <%= f.text_field "linkedin", placeholder: "http://", class:"form-control" %>
  </div>

  <div>
    <%= f.label "password" %><br>
    <%= f.password_field "password", class:"form-control" %>
  </div>
  <div>
    <%= f.label "password_confirmation" %><br>
    <%= f.password_field "password_confirmation", class:"form-control" %>
  </div>
  <br>
  <div><%= f.submit "Submit", class: "btn btn-primary right" %></div>
  
<% end %>

app/views/users/_userprofile.html.erb
<img class="center-block prof-pic" src="<%= @user.picture %>">
<br>
<div class="row">
  <div class="col-md-8 col-md-offset-2">
    <div class="panel well">
      <p class="text-center"><h1><%= @user.firstname %> <%=@user.lastname %></h1></p>
      <p class="text-center"><b>Industry: </b><%= @user.industry %></p>
      <p class="text-center"><%= @user.bio %></p>
    </div>
  </div>
</div>

<div class="row">
  <div class="col-md-8 col-md-offset-2">
    <div class="panel well">
      <h3>Leave a Review:</h3>
      <%= form_for @review, url: reviews_path do |f| %>
        <%= f.text_area :body, class: "form-control" %>
        <br>
        <p>Rating (out of 5):</p>
        <%= f.select :rating, options_for_select([1,2,3,4,5]), {}, class: "form-control" %>
        <br>
        <%= f.hidden_field :reviewee_id, :value => params[:id]%>
        <%= f.hidden_field :reviewer_id, :value => current_user.id %>
        <br>
        <%= f.submit "Create", class: "btn btn-primary" %>
      <% end %>
    </div>
  </div>
</div>

<div class="row">
  <div class="col-md-8 col-md-offset-2">
    <div class="panel well">
      <h3>Current Reviews</h3>
      <% if @reviews.empty? %>
        <p>None yet.</p>
      <% else %> 
        <div class="row">
          <% @reviews.each do |review| %>
            <div class="col-md-10 col-md-offset-1 panel well">
              <p><b>Reviewer: </b><%= @users.where(id: review.reviewer_id).first.firstname %></p>
              <p><b>Rating: </b><%= review.rating %>/5</p>
              <p><i class="fa fa-quote-left fa-lg"></i> <%= review.body %> <i class="fa fa-quote-right fa-lg "></i></p>
              <% if review.reviewer_id == current_user.id %>
                <%= button_to "Delete", "/reviews", {method: :delete, params: {reviewer_id: review.reviewer_id}, class: "btn btn-primary right"} %>
              <% end %>
            </div>
          <% end %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<div class="container">
<div class="well">
  
<% if !current_user %>
  <div class="warning">
    <h1>You don't have a profile! <br>
    Sign up for RideOrbit <%= link_to "here", new_user_path %>.</h1>
  </div>

<% else %>
  
  <img class="center-block prof-pic" src="<%= @user.picture %>">
  <br>
  <p class="text-center"><b>Name:</b> <%= current_user.firstname %> <%=current_user.lastname %></p>
  <p class="text-center"><b>Email:</b> <%= current_user.email %></p>
  <p class="text-center"><b>Phone:</b> <%=current_user.phone %></p>
  <p class="text-center"><b>Industry:</b> <%=current_user.industry %></p>
  <p class="text-center"><b>Bio:</b> <%=current_user.bio %></p>


  <h3>Reviews</h3>
  <% if @reviews.empty? %>
    <p>None yet.</p>
  <% else %>  
  <% @reviews.each do |review| %>
    <p><b>Reviewer: </b><%= @users.where(id: review.reviewer_id).first.firstname %>
    <p><b>Content: </b><%= review.body %></p>
    <p> <b>Rating: </b><%= review.rating %></p>
    <hr>
  <% end %>
  <% end %>

<% end %>
</div>
</div>

app/views/users/new.html.erb
<div class="well-lg">
  <div class="col-md-4 col-md-offset-4">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h3 class="title"><i class="fa fa-user"></i>  Sign up</h3>
      </div>
      <div class="panel-body">
        <%= render 'userform' %>
      </div>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="container">
  
  <% if !current_user %>
    <div class="warning">
      <h1>You don't have a profile! <br>
      Sign up for RideOrbit <%= link_to "here", new_user_path %>.</h1>
    </div>

  <% else %> 
    <%= render 'userprofile' %>
  <% end %>

</div>