config/routes.rb
Rails.application.routes.draw do
  root to: 'static#index'

  get "/newcommute", to: "static#newcommute", as: "newcommute"
  get "/commuteslist", to: "static#commuteslist", as: "commuteslist"
  get "/api/passengercommutes", to: "api_passenger_commutes#retrieve", as: "APIPassengerCommutes"
  get "/drivercommutes/requestinfo", to: "drivercommutes#retrieve", as: "drivercommutes_retrieve"
  get "/passengercommutes/requestinfo", to: "passengercommutes#retrieve", as: "passengercommutes_retrieve"
  get "/goodbye", to: "static#exit", as: "exit"
  resources :map, only: [:index]
  resource :session, only: [:new, :create, :destroy]

  resources :users

  resources :drivercommutes, only: [:create, :destroy, :update]
  resources :passengercommutes, only: [:create, :destroy, :update]
  resources :places, only: [:create, :destroy, :show, :index]
  resource :reviews, only: [:create, :destroy, :show]
  resources :requests, only: [:create, :destroy, :index, :update]
  resources :twilio, only: [:create, :index]
  
end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default orbit-nav">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
     <br><%= link_to image_tag('rideorbit.png'), '/', class: 'logo pull-left' %>
    </div>

    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1" >
      
      <ul class="nav navbar-nav navbar-right">
      <% if current_user.nil? %>
          <li><%= link_to "Sign up", new_user_path%></li>
          <li><%= link_to "Log in", new_session_path %></li>
      <% end %>
      <% if current_user %>
          <% if has_requests %>
            <li><span class="red-badge"><%=existing_requests%></span></li>
          <% end %>
          <li><%= link_to(raw('<i class="fa fa-rocket fa-2x" class="rocket"></i>'), requests_path, style: 'margin-top: 10px', class: 'rocket') %></li>
        <li><%= link_to(raw('<i class="fa fa-globe fa-2x" id="globe" ></i>'), map_index_path, style: 'margin-top: 10px') %></li>

        <li><%= link_to(raw('<i class="fa fa-car fa-2x" id="car" ></i>'), commuteslist_path, style: 'margin-top: 10px') %></li>

        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><img class="dropdown-img" src="<%=current_user.picture%>"><span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
            <li><%= link_to "Profile", users_path %></li>
            <li><%= link_to "Places", places_path %></li> 
            <li><%= link_to "Commutes", commuteslist_path %></li> 
            <li><%= link_to "Make Commute", newcommute_path %></li> 
            <li><%= link_to "Requests", requests_path%></li>
            <li><%= link_to "Logout", "/session", :method => :delete %></li>
          </ul>
        </li>
      <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>




<script type="text/javascript">

$("#commutes-type-toggle").on("click", function(e){
  $("#new-passenger-container").toggleClass("hidden");
  $("#new-driver-container").toggleClass("hidden");
})


</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RideOrbit</title>

  <meta name="viewport" content="width=device-width, initial-scale=1">
  
  <link href='http://fonts.googleapis.com/css?family=Lato' rel='stylesheet' type='text/css'>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  
  <%= javascript_include_tag 'https://maps.googleapis.com/maps/api/js?key=#{ENV["GOOGLE_MAPS_KEY"]}'%>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>

  <%= javascript_include_tag 'bootstrap.min', 'data-turbolinks-track' => true %>

  <%= javascript_include_tag 'nav', 'data-turbolinks-track' => true %>

  <%= yield :head_section %>

  <%= csrf_meta_tags %>

</head>
<body>
  <div id="container">
    <%= render 'layouts/header' %>
    <div class="other-page-bg"></div>
    <%= flash_messages %>
    <%= yield %>
  </div>
</body>

</html>